%% ========================================================================
% DATALOAD FUNCTIONS
% ========================================================================

function [inflow, params, sysparams] = dataload()
    % Load and process hydro simulation data from multiple CSV files
    %
    % Inputs:
    %   n        - number of hydropower units
    %   N        - number of PWL segments for head approximation
    %
    % Outputs:
    %   inflow  - USACE inflow data table
    %   params  - Fitted OLS model parameters for forecasting inflow
    %   sysparams - Reservoir operation parameters
    
    % Define file path
    inflow_path = '/Users/elizacohn/Desktop/cascaded-hydro/simulation-data/inflow.csv';

    %% USACE Inflow Data
    inflow = readtable(inflow_path);
    inflow.datetime = datetime(inflow.datetime, 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
    
    %% Seasonal Forecasting Parameters
    params(1) = struct( ...
        'season',   'dry', ...    % Hydrology season
        'start_day', 250, ...     % Sep 7th (start of dry season)
        'constant', -0.0013, ...  % DDU Params 
        'coef1',    0.83,  ...    % DDU inflow_lag
        'coef2',    0.17,  ...    % DDU outflow_lag  
        'AR_const', 0.0020, ...   % DIU params
        'AR_coef',  0.950, ...    % DIU inflow_lag1
        'AR_std',   0.006, ...    % DIU residual variance % 0.0028
        'omega',    0.0001,  ...  % GARCH-X params  % (0.006^2),
        'alpha',    0.008,   ...  % GARCH-X params % 0.8, 0.008
        'gamma',    0.003);       % GARCH-X params % 6.6e-4 0.003


    %% Hydropower "Per-Unit" Parameters
    sysparams(1) = struct( ...
        'unit',   1, ...      
        'name',   'McNary', ... 
        'a',      2.7, ...    % Hydraulic head coef (max effective voltage)
        'b',      0.45, ...   % Hydraulic head coef (concavity)
        'min_ut', 0.04, ...   
        'max_ut', 0.32, ...
        'min_h',  0, ...
        'max_h',  5.0, ...
        'min_V',  0, ...
        'max_V',  4.0, ...
        'RR_dn',  -0.2, ...
        'RR_up',  0.2, ...
        'F',      1.0, ...
        'V0',     1.2);       % Initial start of charge (30%)

    sysparams(2) = struct( ...
        'unit',   2, ...      
        'name',   'John Day', ... 
        'a',      4.2, ...    
        'b',      0.45, ...   
        'min_ut', 0.04, ...   
        'max_ut', 0.40, ...
        'min_h',  0, ...
        'max_h',  5.0, ...
        'min_V',  0, ...
        'max_V',  1.5, ...
        'RR_dn',  -0.3, ...
        'RR_up',  0.3, ...
        'F',      2.0, ...
        'V0',     0.5);       

    sysparams(3) = struct( ...
        'unit',   3, ...      
        'name',   'Dalles', ... 
        'a',      5.0, ...    
        'b',      0.45, ...   
        'min_ut', 0.04, ...   
        'max_ut', 0.40, ...
        'min_h',  0, ...
        'max_h',  5.0, ...
        'min_V',  0, ...
        'max_V',  1.0, ...
        'RR_dn',  -0.25, ...
        'RR_up',  0.25, ...
        'F',      1.8, ...
        'V0',     0.3); 

    sysparams(4) = struct( ...
        'unit',   4, ...      
        'name',   'Bonneville', ... 
        'a',      4.2, ...    
        'b',      0.45, ...   
        'min_ut', 0.04, ...   
        'max_ut', 0.38, ...
        'min_h',  0, ...
        'max_h',  5.0, ...
        'min_V',  0, ...
        'max_V',  1.5, ...
        'RR_dn',  -0.25, ...
        'RR_up',  0.15, ...
        'F',      1.2, ...
        'V0',     0.5);   
end
