%% ========================================================================
% DATALOAD FUNCTIONS
% ========================================================================

function [inflow, soc, params, sysparams] = dataload()
    % Load and process hydro simulation data from multiple CSV files
    %
    % Outputs:
    %   inflow  - USACE inflow data table
    %   params  - Fitted OLS model parameters for forecasting inflow
    %   sysparams - Reservoir operation parameters
    
    % Define file path
    inflow_path = '/Users/elizacohn/Desktop/cascaded-hydro/simulation-data/inflow-hourly.csv';
    soc_path = '/Users/elizacohn/Desktop/cascaded-hydro/simulation-data/soc.csv';

    % USACE Inflow Data
    inflow = readtable(inflow_path);
    inflow.datetime = datetime(inflow.datetime, 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
    inflow = inflow(:, {'datetime', 'mcn_inflow', 'jda_inflow', 'tda_inflow', 'bon_inflow'});
    inflow.data_year = year(inflow.datetime);
    inflow = movevars(inflow, 'data_year', 'After', 'datetime');

    % 1 kcfs sustained for one hour equals 0.0826446 kaf
    K = 0.0826446;

    % USACE DOC Data 
    soc= readtable(soc_path);
    soc.datetime = datetime(soc.DateTime, 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
    soc = soc(:, {'datetime','mcn_soc', 'jda_soc', 'tda_soc', 'bon_soc'});
    soc.data_year = year(soc.datetime);
    soc = movevars(soc, 'data_year', 'After', 'datetime');
    
    % Seasonal Forecasting Parameters
    % q_t = coef0 + coef1*q_(t-1) + coef2*u_(t-L) (kcfs)
    % std_t = omega + alpha*e_t-1 + beta*std_t-1 + gamma*up_release

    params(1) = struct( ...
        'name',          'John Day', ...
        'unit',          2, ...
        'upstream_unit', 1, ...
        'release_lag',   10, ...
        'coef0',         3.7, ...
        'coef1',         0.90, ...
        'coef2',         0.06, ...
        'AR_std',        6.85, ... %kcfs
        'omega',         NaN, ...
        'alpha',         NaN, ...
        'beta',          NaN, ...
        'gamma_release', NaN, ...
        'gamma_ramp',    NaN, ...
        'nu',            NaN, ...
        ... % Release/ramp normalization used during GARCH training
        'release_min',   NaN, ...
        'release_range', NaN, ...
        'ramp_min',      NaN, ...
        'ramp_range',    NaN);

    params(2) = struct( ...
        'name',          'The Dalles', ...
        'unit',          3, ...
        'upstream_unit', 2, ...
        'release_lag',   3, ...
        'coef0',         6.1, ...
        'coef1',         0.97, ...
        'coef2',         0.03, ...
        'AR_std',        7.18, ... 
        'omega',         NaN, ...
        'alpha',         NaN, ...
        'beta',          NaN, ...
        'gamma_release', NaN, ...
        'gamma_ramp',    NaN, ...
        'nu',            NaN, ...
        'release_min',   NaN, ...
        'release_range', NaN, ...
        'ramp_min',      NaN, ...
        'ramp_range',    NaN);
    
    params(3) = struct( ...
        'name',          'Bonneville', ...
        'unit',          4, ...
        'upstream_unit', 3, ...
        'release_lag',   4, ...
        'coef0',         1.9, ...
        'coef1',         0.95, ...
        'coef2',         0.04, ...
        'AR_std',        3.72, ...
        'omega',         NaN, ...
        'alpha',         NaN, ...
        'beta',          NaN, ...
        'gamma_release', NaN, ...
        'gamma_ramp',    NaN, ...
        'nu',            NaN, ...
        'release_min',   NaN, ...
        'release_range', NaN, ...
        'ramp_min',      NaN, ...
        'ramp_range',    NaN);


    % Hydropower "Per-Unit" Parameters
    sysparams(1) = struct( ...
        'unit',   1, ...      
        'name',   'McNary', ... 
        'a',      1.62, ...    % h_m = a*V_norm + b
        'b',      21.36, ...   
        'min_ut', 0, ...    % kcfs
        'max_ut', 230, ...  % kcfs
        'min_h',  19.7, ...   % m
        'max_h',  23.5, ...   % m
        'min_V',  0, ...      % p.u.
        'max_V',  1.0, ...    % p.u.
        'RR_dn',  -95, ...  % kcfs / hr
        'RR_up',  95, ...   % kcfs / hr
        'F',      980, ...  % MW
        'V0',     0.5, ...
        'kV',     K/234.6);   % p.u. per kcfs-hour     

    sysparams(2) = struct( ...
        'unit',   2, ...      
        'name',   'John Day', ... 
        'a',      3.68, ...    
        'b',      29.17, ...   
        'min_ut', 50, ...   
        'max_ut', 265, ...
        'min_h',  28.3, ...
        'max_h',  32.75, ...
        'min_V',  0, ...
        'max_V',  1.0, ...
        'RR_dn',  -130, ...
        'RR_up',  120, ...
        'F',      2050, ...
        'V0',     .5, ...
        'kV',     K/337.9);   % p.u. per kcfs-hour        

    sysparams(3) = struct( ...
        'unit',   3, ...      
        'name',   'Dalles', ... 
        'a',      3.87, ...    
        'b',      21.76, ...   
        'min_ut', 20, ...   
        'max_ut', 270, ...
        'min_h',  20.5, ...
        'max_h',  26.3, ...
        'min_V',  0, ...
        'max_V',  1.0, ...
        'RR_dn',  -120, ...
        'RR_up',  235, ...
        'F',      1780, ...
        'V0',     0.5, ...
        'kV',     K/41.6);   % p.u. per kcfs-hour  

    sysparams(4) = struct( ...
        'unit',   4, ...      
        'name',   'Bonneville', ... 
        'a',      4.09, ...    
        'b',      16.19, ...   
        'min_ut', 30, ...   
        'max_ut', 260, ...
        'min_h',  12.4, ...
        'max_h',  21.1, ...
        'min_V',  0, ...
        'max_V',  1.0, ...
        'RR_dn',  -120, ...
        'RR_up',  70, ...
        'F',      1150, ...
        'V0',     0.5, ...
        'kV',     K/107.7);   % p.u. per kcfs-hour  
end